#!/bin/bash

if [[ $(make --dry-run -s) ]]
then
  echo make thinks the interpreter is out of date and needs to be re-built
  exit
fi

java -cp $CUP_DIR/java-cup-11b-runtime.jar:. -ea interpreter.Interpreter $*

echo Quandary process returned $?
